# fly.toml app configuration file generated for tasklist02 on 2023-11-20T13:27:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tasklist02"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
